Worksheet-1

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [ ]:
import numpy as np

#num1
empty_array= np.empty((2,2))
print( empty_array)
print("\n")

#num2
all_ones_array= np.ones((4,2))
print(all_ones_array)
print("\n")

#num3
fill_value_array = np.full((3,3),7)
print(fill_value_array)
print("\n")

#num4
my_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(my_array)
print(zeros_like_array)
print("\n")

#num5
my_array = np.array([[1, 2], [3, 4]])
ones_like_array = np.ones_like(my_array)
print(ones_like_array)
print("\n")

#num6
my_list = [1, 2, 3, 4]
numpy_array = np.array(my_list)
print(numpy_array)
print("\n")


[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


[[7 7 7]
 [7 7 7]
 [7 7 7]]


[[0 0]
 [0 0]]


[[1 1]
 [1 1]]


[1 2 3 4]




Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
arr = np.arange(11,50)
print(arr)

matrix = np.arange(9).reshape(3,3)
print(matrix)

identity = np.eye(3)
print(identity)
print("\n")

random_array = np.random.random(size=30)
print(random_array)
print("The mean of the above array is: ",random_array.mean())
print("\n")

random_array = np.random.random((10,10))
print(random_array)
print("Minimum Value is ",random_array.min())
print("Maximum Value is ",random_array.max())
print("\n")

zero_arr = np.zeros(10)
print(zero_arr)
zero_arr[5]=1
print(zero_arr)
print("\n")

arr = [1,2,0,0,4,0]
rev = np.flip(arr)
print(rev)

array = np.zeros((5, 5), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Top border
array[-1, :] = 1  # Bottom border
array[:, 0] = 1  # Left border
array[:, -1] = 1  # Right border

print(array)
print("\n")

# Create an 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
checkerboard[::2, ::2] = 1  # Fill 1 at even rows and even columns
checkerboard[1::2, 1::2] = 1  # Fill 1 at odd rows and odd columns

print(checkerboard)


[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[0.24001431 0.48259165 0.5885965  0.33993604 0.89010244 0.66641117
 0.38301421 0.75045785 0.15329402 0.68657717 0.15095473 0.132555
 0.13283478 0.06099491 0.53970576 0.88343242 0.98985798 0.72719713
 0.02599036 0.21011163 0.70734706 0.07056862 0.320246   0.39277908
 0.73909821 0.31390535 0.9158082  0.37595434 0.86156088 0.78783268]
The mean of the above array is:  0.4839910161892158


[[0.93400849 0.13577206 0.71161817 0.93893358 0.07980872 0.67971368
  0.31680391 0.09652942 0.26096474 0.84042024]
 [0.38319144 0.2084951  0.56829609 0.70750208 0.67834218 0.42291633
  0.20420956 0.40202255 0.24052288 0.29691008]
 [0.48493361 0.96926538 0.86759776 0.56384707 0.7226835  0.82276659
  0.82855745 0.10846479 0.97857973 0.49155855]
 [0.22194928 0.0193737  0.54275998 0.5675949  0.18520974 0.71612494
  0.10162979

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#ques1
array_sum = x + y
print( "Sum: ",array_sum)

# ques2
array_diff = x - y
print("Difference: ",array_diff)

# ques3
array_multiplied = x * 2
print( "Multiplication: ",array_multiplied)

# ques4
array_squared = np.square(x)
print( "Square:", array_squared)

# ques5
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w: ",dot_vw)
print("Dot product of x and v: ",dot_xv)
print("Dot product of x and y: ",dot_xy)

# ques6
concat_xy = np.concatenate((x, y), axis=0)  # Along rows
concat_vw = np.vstack((v, w))  # Along columns
print("Concatenation of x and y: ",concat_xy)
print("Concatenation of v and w: ",concat_vw)

# ques7
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v: ",concat_xv)
except ValueError as e:
    print("Error during concatenation of x and v:", e)


Sum:  [[ 6  8]
 [10 13]]
Difference:  [[-4 -4]
 [-4 -3]]
Multiplication:  [[ 2  4]
 [ 6 10]]
Square: [[ 1  4]
 [ 9 25]]
Dot product of v and w:  219
Dot product of x and v:  [29 77]
Dot product of x and y:  [[19 22]
 [50 58]]
Concatenation of x and y:  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w:  [[ 9 10]
 [11 12]]
Error during concatenation of x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
#part1
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A^-1 = I:")
print(I)

AB = np.dot(A, B)
BA = np.dot(B, A)
AB_not_equal_BA = not np.array_equal(AB, BA)
print("\nAB != BA:", AB_not_equal_BA)

AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
AB_T_equals_BT_AT = np.array_equal(AB_T, BT_AT)
print("\n(AB)^T = B^T * A^T:", AB_T_equals_BT_AT)

A * A^-1 = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB != BA: True

(AB)^T = B^T * A^T: True


In [ ]:
#part2
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution (x, y, z):", X)

Solution (x, y, z): [ 2.  1. -2.]


4.2 How fast is NumPy?

In [3]:
import numpy as np
import time

# Function to measure time taken for an operation
def measure_time(func):
    start_time = time.time()
    func()
    end_time = time.time()
    return end_time - start_time

# 1. Element-wise Addition
def element_wise_addition_python():
    list1 = [i for i in range(1_000_000)]
    list2 = [i for i in range(1_000_000)]
    result = [list1[i] + list2[i] for i in range(len(list1))]

def element_wise_addition_numpy():
    arr1 = np.arange(1_000_000)
    arr2 = np.arange(1_000_000)
    result = arr1 + arr2

print("To Perform Element-wise Addition,")
print(f"Using python lists, it took {measure_time(element_wise_addition_python):.6f} seconds")
print(f"Using numpy array, it took {measure_time(element_wise_addition_numpy):.6f} seconds")

# 2. Element-wise Multiplication
def element_wise_multiplication_python():
    list1 = [i for i in range(1_000_000)]
    list2 = [i for i in range(1_000_000)]
    result = [list1[i] * list2[i] for i in range(len(list1))]

def element_wise_multiplication_numpy():
    arr1 = np.arange(1_000_000)
    arr2 = np.arange(1_000_000)
    result = arr1 * arr2

print("\nTo Perform Element-wise Multiplication,")
print(f"Using python lists, it took {measure_time(element_wise_multiplication_python):.6f} seconds")
print(f"Using numpy array, it took {measure_time(element_wise_multiplication_numpy):.6f} seconds")

# 3. Dot Product
def dot_product_python():
    list1 = [i for i in range(1_000_000)]
    list2 = [i for i in range(1_000_000)]
    result = sum(list1[i] * list2[i] for i in range(len(list1)))

def dot_product_numpy():
    arr1 = np.arange(1_000_000)
    arr2 = np.arange(1_000_000)
    result = np.dot(arr1, arr2)

print("\nTo Perform Dot Product,")
print(f"Using python lists, it took {measure_time(dot_product_python):.6f} seconds")
print(f"Using numpy array, it took {measure_time(dot_product_numpy):.6f} seconds")

# 4. Matrix Multiplication
def matrix_multiplication_python():
    mat1 = [[j for j in range(1000)] for i in range(1000)]
    mat2 = [[j for j in range(1000)] for i in range(1000)]
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*mat2)] for row in mat1]

def matrix_multiplication_numpy():
    mat1 = np.arange(1000*1000).reshape(1000, 1000)
    mat2 = np.arange(1000*1000).reshape(1000, 1000)
    result = np.dot(mat1, mat2)

print("\nTo Perform Matrix Multiplication,")
print(f"Using python lists, it took {measure_time(matrix_multiplication_python):.6f} seconds")
print(f"Using numpy array, it took {measure_time(matrix_multiplication_numpy):.6f} seconds")


To Perform Element-wise Addition,
Using python lists, it took 0.261357 seconds
Using numpy array, it took 0.010768 seconds

To Perform Element-wise Multiplication,
Using python lists, it took 0.233215 seconds
Using numpy array, it took 0.011994 seconds

To Perform Dot Product,
Using python lists, it took 0.230913 seconds
Using numpy array, it took 0.008252 seconds

To Perform Matrix Multiplication,
Using python lists, it took 165.619574 seconds
Using numpy array, it took 1.844171 seconds
